apiVersion: apps/v1
kind: Deployment
metadata:
  name: splitjoin-deployment
spec:
  selector:
    matchLabels:
      app: splitjoin
  replicas: 2
  template:
    metadata:
      labels:
        app: splitjoin
    spec:
      containers:
      - name: splitjoin-container
        image: docker.io/antonyjreynolds/splitjoin:latest
        ports:
        - containerPort: 8080
        env:
          - name: LOGGING
            value: WARNING
